apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: "true"
  name: in-cluster
spec:
  destination:
    namespace: codefresh-default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/codefresh-default/*.yaml,runtimes/codefresh-default/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml}'
      recurse: true
    path: resources
    repoURL: https://github.com/DVdmitry/codefresh-runtime_internal-shared-config3.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
